### PR TITLE
Add various expression functions

### PR DESCRIPTION
**Pull request by sp1187**
This PR adds these expression functions:

- `int(x)` for converting floats to integers
- `float(x)` for converting integers to floats
- `frac(x)` for getting the fractional part of a float
- `abs(x)` for getting the absolute value
- `orga()` for getting the current physical address
- `org()` for getting the current virtual address, same as `.` but added for symmetry
- `headersize()` for getting the current header size

### CODE REVIEW

**Comment by Kingcom** [comment]
Nice additions! But I'm not sure about the latest commit. The reasoning behind evaluating the expression early was to disallow usage of variable labels. For example:
```
.org label
nop
label:
```
This results in an infinite loop when the expression is re-evaluated every iteration. You can still use equ symbols in the pre-evaluated expression, and I could add support for labels that evaluate to a constant (ie. definelabel without any user defined labels in the value).

**Comment by sp1187** [comment]
The reason for that last commit is that I want to be able to use the current virtual/physical addresses in those directives. One example is that you can now use `.org .+N` to skip N bytes.
After I send another PR I'm working on (recalculating the address after a header size change and allowing negative header sizes), it should also support having sections beginning with a specific PC in the middle of the file.

I guess labels might be an issue, but armips seems to handle this case quite well in practice, giving an `Invalid position` error for the problematic `.org` line and a `Stuck in infinite validation loop` error at the end.

**Comment by Kingcom** [comment]
Hm, that does sound handy. Though I may still go back to it later and restrict these expressions to not contain variable labels (so labels that are effectively constants and . would still work), that shouldn't affect the other features.

Just one small thing: please change printError in Validate to queueError, the validation functions are executed repeatedly until everything is stable, and we'll only want to output the errors of the final iteration.

**Comment by sp1187** [comment]
Done. I also noticed that `CDirectiveAlignFill::Validate` uses printError (probably copied my code from there), should I change that too?

**Comment by Kingcom** [comment]
Ah, that's an oversight, yeah. It should also just queue.

**Comment by Kingcom** [comment]
Thanks!

**Pull request merged**
